name: alerta ntfy
on:
  push:
    branches:
      - main   
jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -d "🚀 Código actualizado en el repositorio por ${{ github.actor }}" https://ntfy.sh/devops-itla

